### ISSUE TITLE
Не работает генерация списка студентов, когда в списке группы нет студентов

### ISSUE THREAD

**Issue by dadyarri** [uni-jacob/jacob#120]
```python
future: <Task finished name='Task-73833' coro=<Dispatcher.process_event() done, defined at /usr/local/lib/python3.9/site-packages/vkwave/bots/core/dispatching/dp/dp.py:41> exception=IndexError('list index out of range')>
Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/vkwave/bots/core/dispatching/dp/dp.py", line 70, in process_event
result = await router.process_event(event)
|      |             -> BotEvent(bot_type=BotType.BOT, object=type='message_new' group_id=186618873 object=MessageNewObject(message=MessagesMessage(a...
|      -> <function DefaultRouter.process_event at 0x7fb98f856550>
-> <vkwave.bots.core.dispatching.router.router.DefaultRouter object at 0x7fb98bfd3b80>
File "/usr/local/lib/python3.9/site-packages/vkwave/bots/core/dispatching/router/router.py", line 48, in process_event
h_res = await handler.process_event(event)
|       |             -> BotEvent(bot_type=BotType.BOT, object=type='message_new' group_id=186618873 object=MessageNewObject(message=MessagesMessage(a...
|       -> <function DefaultHandler.process_event at 0x7fb98f84d940>
-> DefaultHandler({'callback': <SimpleBotCallback _start_students bot_type=BotType.BOT>, 'filter_manager': <vkwave.bots.core.dis...
File "/usr/local/lib/python3.9/site-packages/vkwave/bots/core/dispatching/handler/base.py", line 40, in process_event
c_result = await self.callback.execute(event)
|    |        |       -> BotEvent(bot_type=BotType.BOT, object=type='message_new' group_id=186618873 object=MessageNewObject(message=MessagesMessage(a...
|    |        -> <function SimpleBotCallback.execute at 0x7fb98f758f70>
|    -> <SimpleBotCallback _start_students bot_type=BotType.BOT>
-> DefaultHandler({'callback': <SimpleBotCallback _start_students bot_type=BotType.BOT>, 'filter_manager': <vkwave.bots.core.dis...
File "/usr/local/lib/python3.9/site-packages/vkwave/bots/addons/easy/easy_handlers.py", line 224, in execute
return await self.func(new_event)
|    |    -> SimpleBotEvent(bot_type=BotType.BOT, object=type='message_new' group_id=186618873 object=MessageNewObject(message=MessagesMes...
|    -> <function _start_students at 0x7fb98bfcf820>
-> <SimpleBotCallback _start_students bot_type=BotType.BOT>
File "/code/jacob/blueprints/students.py", line 31, in _start_students
keyboard=kbs.contacts.ContactsNavigator(
|   |        -> <class 'jacob.services.keyboard.contacts.ContactsNavigator'>
|   -> <module 'jacob.services.keyboard.contacts' from '/code/jacob/services/keyboard/contacts.py'>
-> <module 'jacob.services.keyboard' from '/code/jacob/services/keyboard/__init__.py'>
File "/code/jacob/services/keyboard/contacts.py", line 20, in menu
kb = kbs.common.alphabet(self.admin_id)
|   |      |        |    -> 62
|   |      |        -> <jacob.services.keyboard.contacts.ContactsKeyboards object at 0x7fb98bf94fd0>
|   |      -> <function alphabet at 0x7fb98c6ed820>
|   -> <module 'jacob.services.keyboard.common' from '/code/jacob/services/keyboard/common.py'>
-> <module 'jacob.services.keyboard' from '/code/jacob/services/keyboard/__init__.py'>
File "/code/jacob/services/keyboard/common.py", line 153, in alphabet
if half[0] == half[-1]:
|          -> []
-> []
IndexError: list index out of range
```

- [ ] Почему так происходит?
- [ ] Почему при создании группы создатель не отмечается как студент?

**Comment by dadyarri** [comment]
- [ ] Почему так происходит?
- [ ] Почему при создании группы создатель не отмечается как студент?

**Comment by dadyarri** [comment]
v3.5.0 won't be released
