### ISSUE TITLE
Не работает загрузка документов

### ISSUE THREAD

**Issue by dadyarri** [uni-jacob/jacob#61]
При попытке загрузить документ(ы) через меню Призыв кидает исключение:
```
-> <class 'vkwave.bots.utils.uploaders.uploader.UploadException'>
vkwave.bots.utils.uploaders.uploader.UploadException: bad_image
```
Трейсбек:

```
Traceback (most recent call last):
File "main.py", line 71, in <module>
bot.run_forever()
|   -> <function BaseSimpleLongPollBot.run_forever at 0x7fec94060670>
-> <vkwave.bots.addons.easy.easy_bot.SimpleLongPollBot object at 0x7fec9bec7af0>
File "/app/.heroku/python/lib/python3.8/site-packages/vkwave/bots/addons/easy/base_easy_bot.py", line 190, in run_forever
loop.run_forever()
|    -> <function BaseEventLoop.run_forever at 0x7fec9a83d160>
-> <_UnixSelectorEventLoop running=True closed=False debug=False>
File "/app/.heroku/python/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
self._run_once()
|    -> <function BaseEventLoop._run_once at 0x7fec9a83cca0>
-> <_UnixSelectorEventLoop running=True closed=False debug=False>
File "/app/.heroku/python/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
handle._run()
|      -> <function Handle._run at 0x7fec9a806ca0>
-> <Handle <TaskWakeupMethWrapper object at 0x7fec8d595040>(<Future finished result=None>)>
File "/app/.heroku/python/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
|    |            |    |           |    -> <member '_args' of 'Handle' objects>
|    |            |    |           -> <Handle <TaskWakeupMethWrapper object at 0x7fec8d595040>(<Future finished result=None>)>
|    |            |    -> <member '_callback' of 'Handle' objects>
|    |            -> <Handle <TaskWakeupMethWrapper object at 0x7fec8d595040>(<Future finished result=None>)>
|    -> <member '_context' of 'Handle' objects>
-> <Handle <TaskWakeupMethWrapper object at 0x7fec8d595040>(<Future finished result=None>)>
File "/app/.heroku/python/lib/python3.8/site-packages/vkwave/bots/core/dispatching/dp/dp.py", line 70, in process_event
result = await router.process_event(event)
|      |             -> BotEvent(bot_type=BotType.BOT, object=type='message_new' group_id=186618873 object=MessageNewObject(message=MessagesMessage(a...
|      -> <function DefaultRouter.process_event at 0x7fec9423f0d0>
-> <vkwave.bots.core.dispatching.router.router.DefaultRouter object at 0x7fec94069b20>
File "/app/.heroku/python/lib/python3.8/site-packages/vkwave/bots/core/dispatching/router/router.py", line 44, in process_event
h_res = await handler.process_event(event)
|       |             -> BotEvent(bot_type=BotType.BOT, object=type='message_new' group_id=186618873 object=MessageNewObject(message=MessagesMessage(a...
|       -> <function DefaultHandler.process_event at 0x7fec942f7670>
-> DefaultHandler({'callback': <vkwave.bots.addons.easy.easy_handlers.SimpleBotCallback object at 0x7fec92ccc8e0>, 'filter_manag...
File "/app/.heroku/python/lib/python3.8/site-packages/vkwave/bots/core/dispatching/handler/base.py", line 40, in process_event
c_result = await self.callback.execute(event)
|    |        |       -> BotEvent(bot_type=BotType.BOT, object=type='message_new' group_id=186618873 object=MessageNewObject(message=MessagesMessage(a...
|    |        -> <function SimpleBotCallback.execute at 0x7fec9404c040>
|    -> <vkwave.bots.addons.easy.easy_handlers.SimpleBotCallback object at 0x7fec92ccc8e0>
-> DefaultHandler({'callback': <vkwave.bots.addons.easy.easy_handlers.SimpleBotCallback object at 0x7fec92ccc8e0>, 'filter_manag...
> File "/app/.heroku/python/lib/python3.8/site-packages/vkwave/bots/addons/easy/easy_handlers.py", line 127, in execute
return await self.func(new_event)
|    |    -> SimpleBotEvent(bot_type=BotType.BOT, object=type='message_new' group_id=186618873 object=MessageNewObject(message=MessagesMes...
|    -> <function register_call_message at 0x7fec92cce0d0>
-> <vkwave.bots.addons.easy.easy_handlers.SimpleBotCallback object at 0x7fec92ccc8e0>
File "/app/blueprints/call.py", line 106, in register_call_message
attachments = await media.load_attachments(
|     -> <function load_attachments at 0x7fec92ca8ee0>
-> <module 'services.media' from '/app/services/media.py'>
File "/app/services/media.py", line 51, in load_attachments
atch = await doc_uploader.get_attachment_from_link(
|            -> <function BaseUploader.get_attachment_from_link at 0x7fec9406f670>
-> <vkwave.bots.utils.uploaders.doc_uploader.DocUploader object at 0x7fec8d591640>
File "/app/.heroku/python/lib/python3.8/site-packages/vkwave/bots/utils/uploaders/uploader.py", line 57, in get_attachment_from_link
return await self.get_attachment_from_io(peer_id, file_data)
|    |                      |        -> <_io.BytesIO object at 0x7fec8d532ea0>
|    |                      -> 549350532
|    -> <function BaseUploader.get_attachment_from_io at 0x7fec9406f4c0>
-> <vkwave.bots.utils.uploaders.doc_uploader.DocUploader object at 0x7fec8d591640>
File "/app/.heroku/python/lib/python3.8/site-packages/vkwave/bots/utils/uploaders/uploader.py", line 43, in get_attachment_from_io
return self.attachment_name(await self.upload(upload_url, f))
|    |                     |    |      |           -> <_io.BytesIO object at 0x7fec8d532ea0>
|    |                     |    |      -> 'https://pu.vk.com/c505536/upload.php?act=add_doc_new&mid=-186618873&aid=-1&gid=0&type=0&peer_id=549350532&rhash=63d5c08d3e7e...
|    |                     |    -> <function DocUploaderMixin.upload at 0x7fec9406f820>
|    |                     -> <vkwave.bots.utils.uploaders.doc_uploader.DocUploader object at 0x7fec8d591640>
|    -> <function DocUploaderMixin.attachment_name at 0x7fec9406f8b0>
-> <vkwave.bots.utils.uploaders.doc_uploader.DocUploader object at 0x7fec8d591640>
File "/app/.heroku/python/lib/python3.8/site-packages/vkwave/bots/utils/uploaders/doc_uploader.py", line 29, in upload
self.handle_error(upload_data)
|    |            -> {'error': 'bad_image', 'error_descr': 'bad_image'}
|    -> <function BaseUploader.handle_error at 0x7fec9406f790>
-> <vkwave.bots.utils.uploaders.doc_uploader.DocUploader object at 0x7fec8d591640>
File "/app/.heroku/python/lib/python3.8/site-packages/vkwave/bots/utils/uploaders/uploader.py", line 68, in handle_error
raise UploadException(err)
|               -> 'bad_image'
-> <class 'vkwave.bots.utils.uploaders.uploader.UploadException'>
vkwave.bots.utils.uploaders.uploader.UploadException: bad_image
```

**Comment by dadyarri** [comment]
Баг пофикшен, ишью закрою, когда верну на место загрузку документов в призыв

**Comment by dadyarri** [comment]
Fixed in 1ecfcfcc3882192389bec10cb0fb1b986f53b297
