### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by MataxeP** [uni-jacob/jacob#74]
Привет! Хотел посмотреть исходный код твоего бота, но при запуске почему-то возникает ошибка.

```python
Traceback (most recent call last):
  File "D:/OneDrive/VKBot/main.py", line 10, in <module>
    from blueprints import call
  File "D:\OneDrive\VKBot\blueprints\call.py", line 16, in <module>
    from services import filters
  File "D:\OneDrive\VKBot\services\filters.py", line 11, in <module>
    from vkwave.bots.core.dispatching.filters.builtin import has_payload
ImportError: cannot import name 'has_payload' from 'vkwave.bots.core.dispatching.filters.builtin' (C:\Users\PMataxe\AppData\Local\Programs\Python\Python38\lib\site-packages\vkwave\bots\core\dispatching\filters\builtin.py)
```

**Comment by dadyarri** [comment]
Привет. Какую ветку запускал?

**Comment by MataxeP** [comment]
Скачивал релиз 2.15.3

**Comment by dadyarri** [comment]
Хм, странно. Попробуй склонить весь репозиторий и перейти в `massive_refactor`. Она точно работает

**Comment by MataxeP** [comment]
Теперь выдаёт такую ошибку
Traceback (most recent call last):
  File "D:/OneDrive/VKBot/jacob/main.py", line 8, in <module>
    from jacob.blueprints.main import main
  File "D:\OneDrive\VKBot\jacob\blueprints\main\main.py", line 6, in <module>
    from jacob.database.utils import students
  File "D:\OneDrive\VKBot\jacob\database\utils\students.py", line 7, in <module>
    from jacob.database.models import Student
  File "D:\OneDrive\VKBot\jacob\database\models.py", line 176, in <module>
    db.bind(provider="postgres", **get_db_credentials(os.getenv("DATABASE_URL")))
  File "C:\Users\PMataxe\AppData\Local\Programs\Python\Python38\lib\site-packages\pony\orm\core.py", line 774, in bind
    self._bind(*args, **kwargs)
  File "C:\Users\PMataxe\AppData\Local\Programs\Python\Python38\lib\site-packages\pony\orm\core.py", line 796, in _bind
    self.provider = provider_cls(*args, **kwargs)
  File "C:\Users\PMataxe\AppData\Local\Programs\Python\Python38\lib\site-packages\pony\orm\dbapiprovider.py", line 130, in __init__
    connection, is_new_connection = provider.connect()
  File "<string>", line 2, in connect
  File "C:\Users\PMataxe\AppData\Local\Programs\Python\Python38\lib\site-packages\pony\orm\dbapiprovider.py", line 72, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

**Comment by dadyarri** [comment]
И неудивительно. Постгрес стоит? База данных нужная настроена? Сомневаюсь. Это не тот проект, который можно запустить без предварительных настроек

**Comment by MataxeP** [comment]
И каким образом мне это сделать?

**Comment by dadyarri** [comment]
У меня пока нет планов на организацию self-hosted версий бота, так что никак. Сейчас запущена свежайшая версия, хочешь потестировать - велкам, дам доступ

**Comment by MataxeP** [comment]
Ну даже если и так, действительно было бы интересно потестить
